BOARD_SYSTEMIMAGE_PARTITION_SIZE ?= 1073741824
BOARD_CACHEIMAGE_PARTITION_SIZE ?= 445644800
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5368709120
ifneq ($(BOARD_USERDATAIMAGE_PARTITION_SIZE),)
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
else
ifneq ($(CALLED_FROM_SETUP),true)
$(warning "BOARD_USERDATAIMAGE_PARTITION_SIZE not defined, please specify at the top of your device's BoardConfig.mk")
endif
endif

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_FLASH_BLOCK_SIZE := 4096

TARGET_BOOTLOADER_IS_2ND := true
TARGET_NO_RECOVERY := true

#Address Configuration settings pertaining to 512MB RAM
BOARD_KERNEL_BASE := 0x0 
BOARD_KERNEL_PAGESIZE := 4096
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x0800000 --ramdisk_offset 0x400000 --second_offset 0x600010

BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true

# Flash partition layout:
BOARD_PRG_FILE ?= device/intel/sofia3g/Sf3g_svb_v1/modem_cfg_emmc.prg

