# Path to ICC from repo
ICC_ROOT_PATH := $(ANDROID_BUILD_TOP)/icc

ICC_PATH := $(ICC_ROOT_PATH)/bin/ia32:$(PPREF)/bin
ICC_LD_LIBRARY_PATH :=  $(ICC_ROOT_PATH)/compiler/lib/ia32
ICC_LIBRARY_PATH := $(ICC_ROOT_PATH)/compiler/lib/ia32
INTEL_LICENSE_FILE := $(ICC_ROOT_PATH)/licenses

PATH := $(ICC_PATH):${PATH}
LD_LIBRARY_PATH := $(ICC_LD_LIBRARY_PATH):${$LD_LIBRARY_PATH}
LIBRARY_PATH := $(ICC_LIBRARY_PATH):${$LIBRARY_PATH}
INTEL_LICENSE_FILE := $(INTEL_LICENSE_FILE):${INTEL_LICENSE_FILE}

export PATH
export LD_LIBRARY_PATH
export LIBRARY_PATH
export INTEL_LICENSE_FILE

