[mixinfo]


[defaults]
video_dec_verisilicon_g1v6=false
video_dec_verisilicon_g2v1=false
video_enc_verisilicon_h1v6=false
video_enc_allegro_al5r=false
image_dec_verisilicon_g1v6=false
audio_dec_intel_vorbis=false
audio_dec_intel_mp3=false
audio_dec_intel_amrnb=false
audio_dec_intel_amrwb=false
audio_dec_intel_aac=false
audio_dec_intel_vorbis=false
audio_enc_intel_aac=false
audio_enc_intel_amrnb=false
audio_enc_intel_amrwb=false