BOARD_EGL_CFG := device/intel/common/graphics/mali/egl.cfg
BOARD_USE_MALI_GFX := true
USE_OPENGL_RENDERER := true
TARGET_DISABLE_TRIPLE_BUFFERING := false
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 5000000
VSYNC_EVENT_PHASE_OFFSET_NS := 7500000
PRESENT_TIME_OFFSET_FROM_VSYNC_NS := 3200000

