BOARD_EGL_CFG := device/intel/common/graphics/mali/egl.cfg
USE_OPENGL_RENDERER := true
TARGET_DISABLE_TRIPLE_BUFFERING := false
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 5000000
VSYNC_EVENT_PHASE_OFFSET_NS := 7500000
BOARD_GRAPHIC_IS_MALI := true
BOARD_SEPOLICY_DIRS += device/intel/sepolicy/graphics/mali-common
