BUILD_MODEM_FROM_SRC := true
BUILD_FWTDS_FROM_SRC := true
BUILD_THREADX_FROM_SRC := true
BUILD_REL10_BOOTCORE := false
BUILD_3GFW_FROM_SRC := true
FW3G_FILENAME := Fwxg631.c
FW3G_PRODUCT := xg631
GEN_PRG_FROM_SRC := true
GEN_THREADX_FLS_FILES := true
GEN_SECBIN_FILES:= true
GEN_OPT_CUSTOM_IMG := true
FASTBOOT_IMG_INCLUDE_SECPACK := false

MODEM_PREBUILT_FLS := $(CURDIR)/$(SOFIA_FW_SRC_BASE)/modem/prebuilt/$(MODEM_PLATFORM)
MODEM_SILENT_RESET_ENABLED := true

