MODEM_BUILD_ARGUMENTS = INT_STAGE=MEX HW_BASE=XG_ES_2.0 UTA_CLIENT=RPC ASM_DEFS_PLATFORM= CBE_UMTSFW_DEVEL=YES CREATEFLS=NO RMV_FEATURE=FEAT_STT_DECODERS PARTITION_XML_INPUT=${PARTITION_XML_PATH} RAMLAYOUT_XML_INPUT=${RAMLAYOUT_XML_PATH} ADD_SYSTEM_DEFS+=LOLLIPOP_PARTITION

