ROCKCHIP_VPU_FEATURES := INCLUDE_VPU_LIBS
ROCKCHIP_VPU_ENABLE := true
ROCKCHIP_GARNET_VPU_ENABLE := true
SOFIA3GR_SF_FEATURES := INCLUDE_SOFIA3GR_SF
INTEL_STAGEFRIGHT := false
BOARD_SEPOLICY_DIRS += \
	device/intel/sepolicy/media \
	device/intel/sepolicy/media/rockchip
