BOARD_RADIOIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_RADIOIMAGE_PARTITION_SIZE := 268435456

BOARD_RADIOIMAGE := $(PRODUCT_OUT)/radio.img
radio_root := $(PRODUCT_OUT)/radio
radio_mountpoint := /radio

$(BOARD_RADIOIMAGE): $(radio_root)
	$(hide) $(MKEXTUSERIMG) -s $(radio_root) $(radio_bin) \
			$(BOARD_RADIOIMAGE_FILE_SYSTEM_TYPE) \
			$(radio_mountpoint) $(BOARD_RADIOIMAGE_PARTITION_SIZE)

$(FACTORY_SCRIPTS_PACKAGE_TARGET): $(BOARD_RADIOIMAGE)

INSTALLED_RADIOIMAGE_TARGET += $(BOARD_RADIOIMAGE)
